---
title: "Equação de Price"
subtitle: Algebra da Evolução
author:
  name: Diogo Melo
  affiliation: IB-USP | 5925935 - Evolução de Fenótipos Complexos
# date: "`r format(Sys.time(), '%d %B %Y')`" ## Or "Lecture no."
output: 
  pdf_document:
    latex_engine: xelatex
    keep_tex: false ## Change to true if want keep intermediate .tex file
    toc: true
    toc_depth: 3
    dev: cairo_pdf
    # fig_width: 7 ## Optional: Set default PDF figure width
    # fig_height: 6 ## Optional: Set default PDF figure height
    extra_dependencies: ['booktabs', 'threeparttable', 'float', 'stmaryrd'] # "longtable"
always_allow_html: true
urlcolor: blue
mainfont: cochineal
sansfont: Fira Sans
monofont: Fira Code ## Although, see: https://tex.stackexchange.com/q/294362
## Automatically knit to both formats:
knit: (function(inputFile, encoding) {
 rmarkdown::render(inputFile, encoding = encoding, 
 output_format = 'all') 
 })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, dpi=300)
```


# Introdução

A equação de Price é um resultado que caminha periclitantemente entre o profundo e o óbvio. Olhando pra essa derivação, veja como, na verdade, a única coisa complicada é definir os termos. Uma vez que os termos estão definidos, os passos são basicamente triviais. Talvez a única complicação seja as relações que nós usamos entre média, variância e covariância. Então eu vou primeiro recapitular a notação que nós usamos em aula e mostrar um pouco mais detalhadamente a relação entre essas quantidades. Mas um aluno competente do primeiro ano de estatística certamente conseguiria fazer todos os passos da dedução sem nenhuma dificuldade. E, se vocês tiverem um pouco de paciência com as somatórias, acho que é perfeitamente possível que vocês consigam reproduzir esse resultado sozinhos.

Em parte, eu diria que o poder da equação de Price é de esclarecer de onde vêm alguns resultados que são apresentados pra gente como tendo sido derivados por grandes homens, do tipo a equação do Criador do Lush, ou a própria equação de resposta da seleção multivariada, que tem o nome mais comum de equação de Lande. O teorema de Price permite a gente recuperar esses resultados muito trivialmente em sala. É, então eu acho que vale a pena ser estudado.

# Resultados importantes em covariação

O estudo de evolução se mistura com o conceito de covariação. Então, um bom entendimento das relações entre médias, variâncias, covariâncias, correlações e coeficientes de regressão é fundamental pra entender esses resultados. Então, uma breve recapitulação.

A média de um conjunto de observações $x_i$ é dada pela seguinte equação e representada pelo seguintes símbolos:

$$
E[x] = \bar {x} = \frac{1}{N} \sum_{i=1}^N x_i
$$
Tanto o simbolo de valor esperado ($E[\cdot]$) quando a barra horizontal ($\bar{\cdot}$) podem ser usado de forma intercambiável para representar a média.

A variáncia de um conjunto de observações é dada pela média dos seus desvios da média:

$$
Var(x) =  \llbracket x \rrbracket 
$$


