---
title: "**5925935** - *Evolução de Fenótipos Complexos*"
output:
  html_document:
    number_sections: false
    toc: true
    theme: yeti
    toc_depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

# Preliminares

## R

Inicialmente, você deve instalar o **R** no seu computador. 
Você pode encontrá-lo no sítio <http://www.r-project.org>.
Neste sítio existem instruções (em inglês) para instalá-lo em vários sistemas operacionais diferentes; versões para Windows, Mac OS e Linux estão disponíveis.
Em suma, vá a um dos espelhos do *Comprehensive R Archive Network* (CRAN), por exemplo <http://brieger.esalq.usp.br/CRAN/>, e siga os links de download e instale o pacote referente ao seu sistema operacional.
Usuários de Linux provavelmente possuem um gerenciador de pacotes instalado em seu sistema, como por
exemplo *apt* ou *dnf*, que podem também ser utilizados para a instalação.

A instalação básica do R no Windows ou MAC OS providencia uma interface básica para execução de rotinas; no entanto, recomendamos a instalação do **R Studio**, uma interface bastante intuitiva para
utilizarmos o R. 
Esta interface pode ser encontrada no sítio <https://posit.co/products/open-source/rstudio> para Windows, MAC OS ou Linux.

O curso foi pensado para pessoas que não são familiarizadas com o R; não esperamos que você seja, a princípio, capaz de escrever rotinas na linguagem. 
Os tutoriais propostos se baseiam em rotinas prontas, uma para cada aula, de modo que estes exercícios consistem em executar estas rotinas, observar e entender o que foi feito, e responder algumas perguntas. 
Assim, estes exercícios servem como ponto de partida para você começar a entender a linguagem. 
Durante o curso, nós vamos introduzir alguns conceitos que são cruciais para o entendimento das rotinas que estamos disponibilizando aqui.

Se você quiser começar a entender a linguagem antes do curso iniciar, recomendamos o sítio <http://ecor.ib.usp.br/doku.php>, da disciplina básica de R oferecida pelo Departamento de Ecologia do IB-USP. 
O link "Atividades Preparatórias" oferece um introdução da linguagem.

# Material de apoio

[Leituras](leituras.zip)

[Apostila de biologia evolutiva](https://github.com/lem-usp/apostila-bio-evol/blob/master/apostila-Bio312.pdf?raw=true)

# Cronograma

```{r, echo=FALSE, warning=FALSE, message=FALSE}
if(!require(knitr)){install.packages("knitr"); library(knitr)}
if(!require(kableExtra)){install.packages("kableExtra"); library(kableExtra)}
dt = data.frame(Dias = paste(rep(c("Segunda", 
                                   "Terça", 
                                   "Quarta", 
                                   "Quinta", 
                                   "Sexta"), each = 2), c("Manhã", "Tarde")),
                Aula =c("Origem, manutenção e organização de variação", "Arquitetura Genética de fenótipos complexos",
                        "Homologia e Mensuração", "Caracterização de variação multidimensional",
                        "Fenótipos moleculares e mapeamento genético", "Paisagem adaptativa fenotípica e seleção natural",
                        "Fenótipos complexos e função", "Evolução de médias fenotípicas I: Introdução aos métodos comparativos filogenéticos", 
                        "Evolução de médias fenotípicas: Métodos comparativos de adaptação e relações fenótipo-ambiente", "Conectando micro- e macroevolução de fenótipos complexos"),
                Tutorial = c("Roda de conversa basico de Evolução", "Introdução ao R - Plantão de Dúvidas",
                             "Introdução à Algebra Linear", "Modelos Lineares Simples e Múltiplos",
                             "Q&A", "Estimando Seleção",
                             "Tutorial de Modelos de Desempenho Funcional",
                             "Métodos Comparativos", "Métodos Comparativos", "Discussão final"),
                Ministrante = c("Monique", "Diogo",
                                "Diogo/Vinicius", "Diogo/Monique",
                                "Diogo", "Diogo/Monique",
                                  "Monique", "Vinicius", "Vinicius", "Diogo/Monique"))

                
dt %>%
  kable() %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

# Aulas Teóricas

### 1. Origem, manutenção e organização de variação fenotípica e genética

+ [Apresentação](Aulas/Historico.pdf)

### 2. *Arquitetura Genética de fenótipos complexos: O mapa genótipo-fenótipo*

+ [Apresentação](Aulas/IntroQuantGen/index.html?presentme=false)

+ Leitura principal: 

    * Hill, W. G. Understanding and using quantitative genetic variation. Philos. Trans. R. Soc. Lond. B Biol. Sci. 365, 73–85 (2010).
  
    * Pavlicev, M. & Cheverud, J. M. Constraints Evolve: Context Dependency of Gene Effects Allows Evolution of Pleiotropy. Annu. Rev. Ecol. Evol. Syst. 46, 413–434 (2015).

+ Leituras complementares: 
  
    * Wilson, Alastair J., Denis Réale, Michelle N. Clements, Michael M. Morrissey, Erik Postma, Craig A. Walling, Loeske E. B. Kruuk, and Daniel H. Nussey. 2010. “An Ecologist’s Guide to the Animal Model.” The Journal of Animal Ecology 79 (1): 13–26.

    * Barton, N. H., A. M. Etheridge, and A. Véber. 2017. “The Infinitesimal Model: Definition, Derivation, and Implications.” Theoretical Population Biology 118 (December): 50–73.


    * Fisher, R. A. 1919. “XV.—The Correlation between Relatives on the Supposition of Mendelian Inheritance.” Earth and Environmental Science Transactions of the Royal Society of Edinburgh 52 (2): 399–433.
  

### 3. *Homologias, Caracteres e Mensurações* 

+ [Apresentação](Aulas/02/index.html?presentme=false)

+ Leituras principais:

    * Wagner, G. P. “What is 'homology thinking' and what is it for?” Journal of Experimental Zoology Part B: Molecular and Developmental Evolution 326, no. 1 (2016): 3–8. doi:10.1002/jez.b.22656.

    * Houle, D., C. Pélabon, G. P. Wagner, T. F. Hansen. “Measurement and Meaning In Biology.” The Quartely Review of Biology 86, no. 1 (2011): 3–34.
    
	  * Ler do início até a seção “Pragmatic Measurement Theory” (13 páginas).

+ Leituras complementares:
  
    * Hansen, T. F., D. Houle. “Measuring and Comparing Evolvability and Constraint in Multivariate Characters.” Journal of Evolutionary Biology 21, no. 5 (2008): 1201–1219. doi:10.1111/j.1420-9101.2008.01573.x.

    * Wagner, G. P., M. D. Laubichler. “Character Identification in Evolutionary Biology: The Role of the Organism.” Theory in Biosciences 119, no. 1 (2000): 20–40.

### 4. *Caracterização de variação em dimensionalidade alta*

+ [Apresentação](Aulas/Quantificando variação multivariada.pdf)

+ Caracteres e matrizes

+ Modelos lineares

+ Componentes principais

+ Caracterização de variação direcional

### 5. *Fenótipos moleculares, mapeamento genético, redes de co-expressão gênica*

+ [Apresentação](Aulas/fenotipos_moleculares.pdf)

+ Leitura principal: 



+ Leituras complementares: 
  


### 6. *Paisagem adaptativa fenotípica e seleção natural*

+ [Apresentação](Aulas/deteccao_modularidade.pdf)

+ Leituras Principais

    * Arnold, Stevan J., Michael E. Pfrender, and Adam G. Jones. 2001. “The Adaptive Landscape as a Conceptual Bridge between Micro- and Macroevolution.” Genetica 112/113: 9–32.

    * Capítulos 6 e 7 do livro: Rice, S.H., 2004. Evolutionary theory: mathematical and conceptual foundations. Sunderland, MA: Sinauer Associates.

+ Leituras adicionais:
  
    * Schluter, Dolph, and Douglas Nychka. 1994. “Exploring Fitness Surfaces.” The American Naturalist 143 (4): 597–616.
  
    * Lande, Russell, and S. J. Stevan J. Arnold. 1983. “The Measurement of Selection on Correlated Characters.” Evolution; International Journal of Organic Evolution 37 (6): 1210.
    * Walsh, Bruce, and Mark W. Blows. 2009. “Abundant Genetic Variation + Strong Selection = Multivariate Genetic Constraints: A Geometric View of Adaptation.” Annual Review of Ecology, Evolution, and Systematics 40 (1): 41–59.


### 7. *Fenótipos complexos e função*

+ [Apresentação](Aulas/paisagem_adaptativa.pdf)

+ Leituras principais:


  
+ Leituras adicionais:
  
    

### 8. *Evolução de médias fenotípicas I: Introdução aos métodos comparativos filogenéticos*

+ [Apresentação](Aulas/)

+ Leituras principais:



+ Leituras complementares:


### 9. *Evolução de médias fenotípicas II: Métodos comparativos de adaptação e relações fenótipo-ambiente*

+ [Apresentação](Aulas/)

+ Leituras principais:



+ Leituras complementares:
  
  
### 10. *Conectando micro- e macroevolução de fenótipos complexos*

+ [Apresentação](Aulas/)

+ Leituras principais:



+ Leituras complementares:
  
  

# Tutoriais

[**Todos os tutoriais em pdf**](Tutoriais/tutoriais_em_pdf.zip)

**Tutorial 1**: [*Introdução ao R*](Tutoriais/inicio.html)

**Tutorial 2**: [*Básico de Álgebra Linear*](Tutoriais/algelin.html)

**Tutorial 3**: [*Modelos Lineares Uni e Multivariados*]()

**Tutorial 4**: [*Estimando Seleção*](Tutoriais/detectando_modularidade.html)

**Tutorial 5**: [*Modelos de Desempenho Funcional*](Tutoriais/selecao.html)

**Tutorial 6**: [*Métodos Comparativos I*](Tutoriais/consequencias_evolutivas.html)

**Tutorial 7**: [*Métodos Comparativos II*](Tutoriais/consequencias_evolutivas.html)


